#!/bin/sh

cd /home/orangepi/pi_flex
mix deps.get
mix compile
sudo /usr/bin/systemctl stop pi_flex.service
rm -rf /home/orangepi/pi_flex/_build/dev/rel
mix release
sudo /usr/bin/systemctl start pi_flex.service

# git update-index --chmod=+x post-merge